### ISSUE TITLE
Compiles in arduino IDE, but not using platformIO....

### ISSUE THREAD

**Issue by p-sims** [NitrofMtl/ADC_SEQR#4]
The example from ADC_SEQR library compile find in Arduino IDE, but If I copy that same code into a PlatformIO project it produced some odd compilation error message that seem to relate the library conflicting with some board framework files:
.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/component/component_adc.h:137:0

`---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Verbose mode can be enabled via `-v, --verbose` option
CONFIGURATION: https://docs.platformio.org/page/boards/atmelsam/######-prototype.html
PLATFORM: Atmel SAM (7.0.0) > ###### Protype SAM3X8E
HARDWARE: AT91SAM3X8E 84MHz, 96KB RAM, 512KB Flash
DEBUG: Current (custom) External (atmel-ice, blackmagic, jlink, stlink)
PACKAGES: 
 - framework-arduino-sam 1.6.12 
 - framework-cmsis 1.40500.0 (4.5.0) 
 - framework-cmsis-atmel 1.2.2 
 - toolchain-gccarmnoneeabi 1.70201.0 (7.2.1)
LDF: Library Dependency Finder -> https://bit.ly/configure-pio-ldf
LDF Modes: Finder ~ chain, Compatibility ~ soft
Found 7 compatible libraries
Scanning dependencies...
Dependency Graph
|-- <Ethernet> 2.0.0
|   |-- <SPI> 1.0
|-- <ADC_SEQR> 2.4.0
|-- <Bolder Flight Systems SBUS> 2.1.2
|-- <SPI> 1.0
Building in release mode
Compiling .pio/build/######_v2/src/main.cpp.o
Compiling .pio/build/######_v2/lib7f4/SPI/SPI.cpp.o
In file included from include/standardFuncs.cpp:10:0,
                 from include/cna1Funcs.cpp:8,
                 from src/main.cpp:24:
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:18:0: warning: "ADC_MR_TRANSFER" redefined
 #define ADC_MR_TRANSFER(x) ( x & BIT_FIELD(2) ) << 28
 
In file included from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/sam3x8e.h:273:0,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/sam3xa.h:44,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3.h:59,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam.h:198,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/libsam/chip.h:25,
                 from /Users/######/.platformio/packages/framework-arduino-sam/cores/arduino/Arduino.h:42,
                 from include/standardFuncs.cpp:6,
                 from include/cna1Funcs.cpp:8,
                 from src/main.cpp:24:
/Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/component/component_adc.h:140:0: note: this is the location of the previous definition
 #define ADC_MR_TRANSFER(value) ((ADC_MR_TRANSFER_Msk & ((value) << ADC_MR_TRANSFER_Pos)))
 
In file included from include/standardFuncs.cpp:10:0,
                 from include/cna1Funcs.cpp:8,
                 from src/main.cpp:24:
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:19:0: warning: "ADC_MR_TRACKTIM" redefined
 #define ADC_MR_TRACKTIM(x) ( x & BIT_FIELD(4) ) << 24
 
In file included from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/sam3x8e.h:273:0,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/sam3xa.h:44,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3.h:59,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam.h:198,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/libsam/chip.h:25,
                 from /Users/######/.platformio/packages/framework-arduino-sam/cores/arduino/Arduino.h:42,
                 from include/standardFuncs.cpp:6,
                 from include/cna1Funcs.cpp:8,
                 from src/main.cpp:24:
/Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/component/component_adc.h:137:0: note: this is the location of the previous definition
 #define ADC_MR_TRACKTIM(value) ((ADC_MR_TRACKTIM_Msk & ((value) << ADC_MR_TRACKTIM_Pos)))
 
In file included from include/standardFuncs.cpp:10:0,
                 from include/cna1Funcs.cpp:8,
                 from src/main.cpp:24:
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:22:0: warning: "ADC_MR_PRESCAL" redefined
 #define ADC_MR_PRESCAL(x)  ( x & BIT_FIELD(8) ) << 8
 
In file included from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/sam3x8e.h:273:0,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/sam3xa.h:44,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3.h:59,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam.h:198,
                 from /Users/######/.platformio/packages/framework-arduino-sam/system/libsam/chip.h:25,
                 from /Users/######/.platformio/packages/framework-arduino-sam/cores/arduino/Arduino.h:42,
                 from include/standardFuncs.cpp:6,
                 from include/cna1Funcs.cpp:8,
                 from src/main.cpp:24:
/Users/######/.platformio/packages/framework-arduino-sam/system/CMSIS/Device/ATMEL/sam3xa/include/component/component_adc.h:107:0: note: this is the location of the previous definition
 #define ADC_MR_PRESCAL(value) ((ADC_MR_PRESCAL_Msk & ((value) << ADC_MR_PRESCAL_Pos)))
 
Compiling .pio/build/######_v2/libc42/Ethernet/Dhcp.cpp.o
Compiling .pio/build/######_v2/libc42/Ethernet/Dns.cpp.o
In file included from include/standardFuncs.cpp:10:0,
                 from include/cna1Funcs.cpp:8,
                 from src/main.cpp:24:
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h: In instantiation of 'void enableChX(Pin, PinX ...) [with Pin = int; PinX = {}]':
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:48:53:   required from 'static void Adc_Seqr::begin(PinX ...) [with PinX = {int}]'
src/main.cpp:179:32:   required from here
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:41:83: error: no matching function for call to 'enableChX()'
 static void enableChX(Pin pin, PinX ... pinX) { enableChX((uint8_t)pin); enableChX((uint8_t)pinX...); };
                                                                          ~~~~~~~~~^~~~~~~~~~~~~~~~~~
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:31:13: note: candidate: void enableChX(uint8_t)
 static void enableChX(uint8_t pin){
             ^~~~~~~~~
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:31:13: note:   candidate expects 1 argument, 0 provided
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:41:13: note: candidate: template<class Pin, class ... PinX> void enableChX(Pin, PinX ...)
 static void enableChX(Pin pin, PinX ... pinX) { enableChX((uint8_t)pin); enableChX((uint8_t)pinX...); };
             ^~~~~~~~~
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:41:13: note:   template argument deduction/substitution failed:
.pio/libdeps/######_v2/ADC_SEQR/src/ADC_SEQR.h:41:83: note:   candidate expects at least 1 argument, 0 provided
 static void enableChX(Pin pin, PinX ... pinX) { enableChX((uint8_t)pin); enableChX((uint8_t)pinX...); };
                                                                          ~~~~~~~~~^~~~~~~~~~~~~~~~~~
*** [.pio/build/######_v2/src/main.cpp.o] Error 1
========================================================================== [FAILED] Took 2.75 seconds ==========================================================================
The terminal process "platformio 'run'" terminated with exit code: 1.`

My platformio.ini file looks like:
`platform = atmelsam
board = custom_due
framework = arduino
upload_protocol = sam-ba
debug_tool = custom
debug_server = 
	$PROJECT_PACKAGES_DIR/tool-openocd/bin/openocd
	-s
	$PROJECT_PACKAGES_DIR/tool-openocd/scripts
	-f interface/cmsis-dap.cfg
	-c
	"transport select swd"
	-c
	"set CHIPNAME at91sam3X8E"
	-f
	target/at91sam3ax_8x.cfg
lib_deps = 
	arduino-libraries/Ethernet@^2.0.0
	nitrofmtl/ADC_SEQR@^2.4

[platformio]

**Comment by NitrofMtl** [comment]
Seem the main error came from the example: I add the prototype for the printAdcFcy(); at the to pf the sketch make it compile.

But it was still got a lot of warning du to macro duplicate, that was not the case on arduino IDE but there in PIO. It is fix.

you can update to version 2.4.2 with pio lib update or you can fetch it directly from github.

Thanks.
